aws:
    version: "2016-11-15"
    region: "%env(AWS_EC2_SERVICE_ENDPOINT)%"
    credentials:
        key: "%env(AWS_KEY)%"
        secret: "%env(AWS_SECRET)%"
    Pricing:
        version: "2017-10-15"
        region: "%env(AWS_PRICE_LIST_SERVICE_ENDPOINT)%"
