endroid_qr_code:
    default:
        writer: Endroid\QrCode\Writer\PngWriter
        size: 640
        margin: 10
        encoding: 'UTF-8'
        roundBlockSizeMode: 'margin' # 'low', 'medium', 'quartile', or 'high'
        errorCorrectionLevel: 'low'
        validateResult: false
    custom:
        logoPath: '%kernel.project_dir%/public/moon.png'
        logoResizeToWidth: 150
