App\Entity\Attendees:
    properties:
        name:
            - NotBlank:
                message: 'attendees.name.not_blank'
                groups: create
            - Length:
                minMessage: 'attendees.name.minMessage'
                maxMessage: 'attendees.name.maxMessage'
                min: 2
                max: 50
                groups: create
